### ISSUE TITLE
SetupCompileMode with CppCompileNoRpc compile error

### ISSUE THREAD

**Issue by RizHuang** [Microsoft/AirSim#101]
In the AirSim.Build.cs I select the 
` SetupCompileMode(CompileMode.CppCompileNoRpc, Target);`
After compiled it show me such errors : 
LNK1120 
Failed to produce item ***\UE4Editor-AirSim.dll
MSB3075: command "e:\Program Files\Epic Games\UE_4.14\Engine\Build\BatchFiles\Build.bat" flightEditor Win64 Development "C:\Users\RizHuang\Documents\Unreal Projects\flight\flight.uproject"  exit code 5. Mak

**Comment by sytelus** [comment]
These are advanced compilation options, typically useful for debugging. We haven't exposed them via documentation so use it your own risk :). In above case, CppCompileNoRpc means that instead of relying on precompiled lib files in deps folder, we will have Unreal compile cpp files. This should normally work fine except for the case of rpc related cpp because they require C++14. Unfortunately Unreal has restricted their build to C++11 so you have exclude rpc related stuff. 

Anyway, if you think this is getting too complex, I would suggest wait for a while until I get around refactoring this part and documenting it.
