### ISSUE TITLE
REPORT A PROBLEM. There is no moving human in Latest release(v1.1.10) in drone mode?

### ISSUE THREAD

**Issue by allen9273** [microsoft/AirSim#1047]
The latest release of CityEnviron performs much better than before, but when I switch it to drone mode, there is no any moving human and very small amount of moving cars.

**Comment by jonyMarino** [comment]
Closed due to age and incompleteness.
Please feel free to open a new issue if you still have this problem, and include the following (as requested when opening a bug issue)

*Make sure to write all reproduction steps
*Include full error message in text form
*Search issues for error message before filing issue
*Attach screenshot if applicable
*Include code to run if applicable

Thanks!
