### ISSUE TITLE
where is the vehicle spawned? 

### ISSUE THREAD

**Issue by husha1993** [Microsoft/AirSim#1182]
Hi,

https://github.com/Microsoft/AirSim/blob/master/docs/apis.md#coordinate-system
" The vehicle is spawned in Unreal environment where the Player Start component is placed. "
While it seems that the vehicle is spawned in a lower position than the Player Start component.

**Comment by sytelus** [comment]
Vehicle is spawned at Player Start but because vehicle's body origin is not the bottom (its center) it would get spawned bit above and after spawning it will fall due to gravity a small distance.

Here's the code: https://github.com/Microsoft/AirSim/blob/59679c07d0ab605f662090bb10c85302508bd518/Unreal/Environments/Blocks/Plugins/AirSim/Source/Vehicles/Multirotor/SimModeWorldMultiRotor.cpp#L110
