### ISSUE TITLE
Timeout problem of a function like land()?

### ISSUE THREAD

**Issue by vinbo** [microsoft/AirSim#1206]
the error occurred when my drone is high enough, and cannot land to ground in 60s. then UE editor shut down itself.( I'm under ubuntu 16.04 lts, ue4.17, airsim v1.1.10)

the error info is like this: "terminating with uncaught exception of type rpc::timeout: rpc::timeout: Timeout of 60000ms while calling RPC function 'land'
已放弃 (核心已转储)"

sorry for the chinese code, which means "already abandoned(kernel has been transferred and restored)

so, is this a bug or do i have to write my own land() to lower it down and then call the land()?

**Comment by vinbo** [comment]
my experience seems like, land() is not the only function that has such property?

**Comment by jonyMarino** [comment]
Closed due to age and incompleteness.
Please feel free to open a new issue if you still have this problem, and include the following (as requested when opening a bug issue)

*Make sure to write all reproduction steps
*Include full error message in text form
*Search issues for error message before filing issue
*Attach screenshot if applicable
*Include code to run if applicable

Thanks!
