### ISSUE TITLE
Can't Lunch Drone in Unreal Engine when try to test Flying

### ISSUE THREAD

**Issue by Focke-Wulf** [Microsoft/AirSim#121]
Hi All
I just come back to use 4.14 and follow the set up environment and build the Plugins.. every thing goes fine...

but when i click the play button...

Nothing happened... no controls and no Drone lunch into the environment...
here is my floder
![3](https://cloud.githubusercontent.com/assets/26343300/24082200/9c2f22ac-0d15-11e7-8993-7baed29c0d6e.PNG)

this is the test environment...
![4](https://cloud.githubusercontent.com/assets/26343300/24082201/9f787ef4-0d15-11e7-8bee-229020f71dc2.PNG)

when i click the play button....it only shows like this..
![5](https://cloud.githubusercontent.com/assets/26343300/24082204/a3aedb08-0d15-11e7-837c-ba176de893e3.PNG)

how should i fix this ?
Thanks!

**Comment by Timebutt** [comment]
You'll need to switch to Unreal Editor 4.15, 4.14 is no longer supported. See  https://github.com/Microsoft/AirSim/issues/116#issuecomment-287512253.

**Comment by Focke-Wulf** [comment]
When i am trying to rebuild the project from 4.14 to 4.15 
it shows ...
![2](https://cloud.githubusercontent.com/assets/26343300/24095039/69b32086-0daf-11e7-829c-568a1219abbe.PNG)

i have no idea why ....

**Comment by saihv** [comment]
Instead of clicking on 'Yes' when Unreal asks whether to rebuild the dll, did you try 'Generate Project Files' and then building directly from Visual Studio as mentioned in the instructions?

**Comment by lovettchris** [comment]
Note, you have to use 4.15 if you are on the latest AirSim bits because the drone asset in the blueprint only works on 4.15.  To use 4.14 you would have to use the "Unreal4.14" branch that created, but that branch will not be getting updates to the code.

As for the screen shot you included, you might try changing PlayerStart location to be closer to the ground as I show in this [airsim setup video](https://www.youtube.com/watch?v=1oY8Qu5maQQ&feature=youtu.be).

**Comment by Focke-Wulf** [comment]
Thanks for the help. i am now fix this problem!!!
