### ISSUE TITLE
Velocity of BP_FlyingPawn acquired by "Get Physics Linear Velocity" is very noisy (while SuvCarPawn is fine)

### ISSUE THREAD

**Issue by KubaFYI** [microsoft/AirSim#1223]
I am implementing new ImageType which dynamically depends on the pawn velocity. Currently I use the [Get Physics Linear Velocity](http://api.unrealengine.com/INT/BlueprintAPI/Physics/GetPhysicsLinearVelocity/) function on the pawn's Body Mesh to extract that velocity and use it within Unreal as such:

![velocity sample](https://user-images.githubusercontent.com/5529099/42245103-7369e2b8-7f0f-11e8-842f-e4f3087c9fe1.PNG)

Unfortunately the velocity I get ends up very noisy, as clearly visible in my new ImageType (the second sub-window below), and kinda visible in the way the velocity magnitude printed in the upper left corner jumps around.

![showyperfectboar-max-14mb](https://user-images.githubusercontent.com/5529099/42245373-7a31c8bc-7f10-11e8-8e8c-8da8f54a1003.gif)

What I found curious is that when I apply the same procedure to a Car simulation, the result is just fine, as seen below.

![admirablepersonalivorybackedwoodswallow-max-14mb](https://user-images.githubusercontent.com/5529099/42245401-9a6edca0-7f10-11e8-867d-7c57892df2a9.gif)

Is this a known problem? Any ideas on how to fix this, or at least some alternative ways of reading the vehicle velocity into a post-process material?

**Comment by jonyMarino** [comment]
Closed due to age and incompleteness.
Please feel free to open a new issue if you still have this problem, and include the following (as requested when opening a bug issue)

*Make sure to write all reproduction steps
*Include full error message in text form
*Search issues for error message before filing issue
*Attach screenshot if applicable
*Include code to run if applicable

Thanks!
