### ISSUE TITLE
settings.json turns back to default.

### ISSUE THREAD

**Issue by WadeWuu** [microsoft/AirSim#1383]
I have already changed settings.json. But when I restart the project of UE, settings.json will  turns back to default. I can not understand.

**Comment by WadeWuu** [comment]
I want to use multiple vehicles. So, I change setting.json like that.
{
	"SettingsVersion": 1.2,
	"SimMode": "Car",
	
	"Vehicles": {
		"Car1": {
		  "VehicleType": "PhysXCar",
		  "X": 4, "Y": 0, "Z": -2
		},
		"Car2": {
		  "VehicleType": "PhysXCar",
		  "X": -4, "Y": 0, "Z": -2,
      "Yaw": 90
		}
  }
}

But, when I start the project, it turns to the default.
{
  "SeeDocsAt": "https://github.com/Microsoft/AirSim/blob/master/docs/settings.md",
  "SettingsVersion": 1.2
}

**Comment by sytelus** [comment]
That's strange. Do you have non-english OS? I suspect there is a bug in code that checks if file already exist and it doesn't take in to account unicode characters.

**Comment by madratman** [comment]
@WadeWuu any updates? was this resolved?

**Comment by jonyMarino** [comment]
Closed due to age and incompleteness.
Please feel free to open a new issue if you still have this problem, and include the following (as requested when opening a bug issue)

*Make sure to write all reproduction steps
*Include full error message in text form
*Search issues for error message before filing issue
*Attach screenshot if applicable
*Include code to run if applicable

Thanks!
