### ISSUE TITLE
Nested font faces warning

### ISSUE THREAD

**Issue by TritonSailor** [microsoft/AirSim#1417]
Found this packaging issue:

UATHelper: Packaging (Linux):   [33mLogFontFace: Warning: The font asset '/AirSim/HUDAssets/DebugWidgetMonospace.DebugWidgetMonospace' contains nested font faces which can cause issues for iterative cook-on-the-fly. Please edit the font asset and split the font faces into their own assets.
UATHelper: Packaging (Linux):   [0mLogFontFace: Warning: The font asset '/AirSim/HUDAssets/DebugWidgetMonospace.DebugWidgetMonospace' contains nested font faces which can cause issues for iterative cook-on-the-fly. Please edit the font asset and split the font faces into their own assets.
PackagingResults: Warning: The font asset '/AirSim/HUDAssets/DebugWidgetMonospace.DebugWidgetMonospace' contains nested font faces which can cause issues for iterative cook-on-the-fly. Please edit the font asset and split the font faces into their own assets.
PackagingResults: Warning: The font asset '/AirSim/HUDAssets/DebugWidgetMonospace.DebugWidgetMonospace' contains nested font faces which can cause issues for iterative cook-on-the-fly. Please edit the font asset and split the font faces into their own assets.

**Comment by jonyMarino** [comment]
Closed due to age and incompleteness.
Please feel free to open a new issue if you still have this problem, and include the following (as requested when opening a bug issue)

*Make sure to write all reproduction steps
*Include full error message in text form
*Search issues for error message before filing issue
*Attach screenshot if applicable
*Include code to run if applicable

Thanks!
