### ISSUE TITLE
Reinforcement-learning optimises to minimum reward

### ISSUE THREAD

**Issue by tvturnhout** [microsoft/AirSim#1473]
We have created a custom world with checkpoints and using the DQN algorithm by Microsoft (https://github.com/dennybritz/reinforcement-learning/tree/master/DQN) to learn the drone navigate through it.

We defined a reward function as:

- Previous distance to target - Current distance to target
- Reward for crossing a checkpoint

This results in the drone getting a positive reward for moving towards objectives and vice versa. Passing through a checkpoint gives a big reward and activates the next one.

However, after training for a couple of days on two 1080ti's  @ 5 x clock speed, the drone started flying away from the target and seems to optimise to a minium reward (here is a picture of the tensorboard: https://i.imgur.com/RuBc9GE.png).  Am I missing something?

All the help is welcome!

**Comment by jonyMarino** [comment]
Closed due to age and incompleteness.
Please feel free to open a new issue if you still have this problem, and include the following (as requested when opening a bug issue)

*Make sure to write all reproduction steps
*Include full error message in text form
*Search issues for error message before filing issue
*Attach screenshot if applicable
*Include code to run if applicable

Thanks!
