### ISSUE TITLE
Multiple Drones Reset

### ISSUE THREAD

**Issue by seragENTp** [microsoft/AirSim#1475]
I'm trying to reset specific drone to its initial position (Not the all drones) but client.reset() resets all the drones to its initial position. I  tried to use simSetVehiclePose to reset a specific drone but it seems that it doesn't ignore collision (by setting ignore_collision = True). So what could be the proper way to do this ?

**Comment by jonyMarino** [comment]
Closed due to age.
Please feel free to open a new issue (referring to this one) if you still have this problem, and include the following (as requested when opening a bug issue)

*Make sure to write all reproduction steps
*Include full error message in text form
*Search issues for error message before filing an issue
*Attach a screenshot if applicable
*Include code to run if applicable

Thanks!
