### ISSUE TITLE
is there a way to get the instance segementation label?

### ISSUE THREAD

**Issue by 1453042287** [Microsoft/AirSim#1554]
like the title, i'm new here, thanks a lot!

**Comment by madratman** [comment]
Please read [the segmentation section here](https://github.com/Microsoft/AirSim/blob/123bbd6d6416bbe98e775101ba8ebcb5ccbf8501/docs/image_apis.md#segmentation) and [the section on getting mesh names](https://github.com/Microsoft/AirSim/blob/123bbd6d6416bbe98e775101ba8ebcb5ccbf8501/docs/image_apis.md#how-to-find-mesh-names). 
You should be able to set object IDs (`simSetSegmentationObjectID`) according to your needs in the files linked in the above sections. 

This sentence is useful : `Notice that typical Unreal environments, like Blocks, usually have many other meshes that comprises of same object, for example, "Ground_2", "Ground_3" and so on. As it is tedious to set object ID for all of these meshes, AirSim also supports regular expressions.`
Instead of a regex, you'd have to manually set IDs / get the IDs and check the color values [here](https://github.com/Microsoft/AirSim/blob/42d4d91e7a7a7f037036c98c31b7537989f2a6e6/docs/seg_rgbs.txt)

**Comment by 1453042287** [comment]
@madratman thank you for your reply!

**Comment by chongjeelee** [comment]
How can i get instance segmentation label in lidar ?
