### ISSUE TITLE
the seg_rgbs.txt seems to be out of date

### ISSUE THREAD

**Issue by MageekChiu** [microsoft/AirSim#1556]
I get object id by name  manually ,then I get rgb by id from seg_rgbs.txt as  the [doc](https://github.com/Microsoft/AirSim/blob/master/docs/image_apis.md#startup-object-ids) here says.
but the color doesn't seems to be same as the sub window 2 shows  .

```
def getIdbyName(names):
    names = names.lower()
    hashId = 0
    for chara in names:
        asciiCode = ord(chara)
        if asciiCode>=97  :
            hashId += asciiCode
    
    hashId %= 256 
    return hashId

def getCollorById(hashId):
    return rgbList[hashId]# from seg_rgbs.txt

collorRGB = getCollorById(getIdbyName("Truck"))
print collorRGB
img = Image.new('RGB', (500,500), tuple(collorRGB))
img.show()
```

version: win10, airsim1.0

**Comment by espenthaem** [comment]
Has this been looked into yet?

**Comment by jonyMarino** [comment]
Closed due to age and incompleteness.
Please feel free to open a new issue if you still have this problem, and include the following (as requested when opening a bug issue)

*Make sure to write all reproduction steps
*Include full error message in text form
*Search issues for error message before filing issue
*Attach screenshot if applicable
*Include code to run if applicable

Thanks!
