### ISSUE TITLE
AirSim low FPS on Windows

### ISSUE THREAD

**Issue by EliaTarasov** [Microsoft/AirSim#164]
Hello!

OS: Windows 10
CPU: Intel Core i3-6100T 3.2GHz
RAM: 8GB
Graphics: Intel HD Graphics 530

Problem:
AirSim successfully run on Unreal with/without Visual Studio, but for all Visual Studio's build configs FPS are very slow, usually 1-5 FPS.
What's the reason might be?

Thanks!

**Comment by sytelus** [comment]
I think the problem is that your machine is 2 cores. Currently AirSim runs physics thread on high priority and would probably utilize one core by itself. I would say less than quadcore machines would have difficult time to get good FPS. We had like to improve this but its not very high priority right now  so please feel free to contribute this in area.
