### ISSUE TITLE
Fixed wing support in AirSim

### ISSUE THREAD

**Issue by yashkaushal** [Microsoft/AirSim#1679]
Does AirSim Support Fixed wing simulation or has plan to include the support for fixed wing simulation?

**Comment by madratman** [comment]
Currently, no. We don't have the bandwidth in the near future for this. 

If you want to try implement a fixed wing, you'll have to start looking at the code for the physics of a single rotor [here](https://github.com/Microsoft/AirSim/blob/master/AirLib/include/vehicles/multirotor/Rotor.hpp), the rotor class is derived from a [physicsbodyvertex](https://github.com/Microsoft/AirSim/blob/master/AirLib/include/physics/PhysicsBodyVertex.hpp). Instead of rotor, you'd have to make a `Wing`, add a lift force, change the thrust vector, etc. You can also look at how the [multirotor](https://github.com/Microsoft/AirSim/blob/master/AirLib/include/vehicles/multirotor/MultiRotor.hpp) and the [simpleflight firmware](https://github.com/Microsoft/AirSim/tree/master/AirLib/include/vehicles/multirotor/firmwares/simple_flight) works. 
that's a lot of work :)

@sytelus might have better ideas?

**Comment by RVBldr** [comment]
We also had interns work with Easy Flight Model, which seemed to do OK: https://www.unrealengine.com/marketplace/easy-flight-model

**Comment by AOS55** [comment]
> We also had interns work with Easy Flight Model, which seemed to do OK: https://www.unrealengine.com/marketplace/easy-flight-model

@RVBldr thats an interesting way to do it were you able to just add it in as a vehicle in AirSim/Source/AirLib/include/vehicles? I would be really interested to hear some more details do you have any of the source code available open source?

**Comment by nikitabeebe** [comment]
@RVBldr Could you contact me or provide more information regarding the application and success/issue with integrating the Easy Flight Model into UE4 with AirSim environment? Akin to what @AOS55 mentioned, I'm looking into implementing a fixed wing model using AirSim, but hoping to avoid a full on refactorization of the simulation.
