### ISSUE TITLE
Can I control a drone from a fixed, 3rd-person viewpoint?

### ISSUE THREAD

**Issue by DTChuck** [microsoft/AirSim#1709]
I am working on a project where I would like a human player character to be able to interact in the same environment that an AirSim drone is flying in. This means that an API controlled drone would be flying around, and the human would be controlling their own character (FPS style or 3rd-Person, not specifically requiring either one), and they would exist in the same environment. I am working in the Unreal Engine. Is this possible under the current architecture of AirSim, and if not, what might I need to address to get it working?

**Comment by DavidLSmyth** [comment]
I'm pretty sure this would be awkward to do using an unreal engine character since the game mode needs to be set to AirSimGame and changing/merging it with another seems to be difficult (as outlined in #506). I wanted the same functionality but wanted to spend as little time as possible doing it, so I added a level blueprint that moved the perspective to a camera dropped in the game when the c key was pressed. I then added key bindings to wsad which performed a translation (up down left right) on the camera, it was pretty close to fpv. I also added extra cameras in locations I wanted to view the drone from and set up a key binding to move from one to the next. I can try to dig up the blueprint if you think it would solve your problem.
