### ISSUE TITLE
Jupyter stuck in * when calling car client

### ISSUE THREAD

**Issue by wonjoonSeol** [Microsoft/AirSim#1731]
Hello,

Everytime I call car client, the cell completes its execution as can be seen from the print statement in the image below, but the following cells are stuck in astericks. 

It never runs.

<img width="903" alt="screenshot 2019-01-23 at 07 16 16" src="https://user-images.githubusercontent.com/22602022/51589429-d95f8680-1ede-11e9-9c53-8b1914927f3f.png">

This is one example, but it happens to all other cells that uses car client API.

Windows 10, Airsim v1.2.1 - Windows binary (Not built), python 3.6.8,  jupyter 4.4.0

**Comment by madratman** [comment]
@wonjoonSeol in general, instead of a screenshot, please post python code, for ease in reproduction of your issue. 
I think the script is stuck as `plt.imshow()` is a blocking call. you can simply comment the imshow() line, or better still either pass the non-blocking parameter, or use the interactive mode, as explained [here](https://stackoverflow.com/questions/28269157/plotting-in-a-non-blocking-way-with-matplotlib)

**Comment by wonjoonSeol** [comment]
Thank you for the comment, 
plt was not the cause of the issue here.

Share.scripts_downpour.app.airsim_client from DistributedRL guide that overriden CarClient call was the issue.

[AutonomousDrivingCookbook/issues/85](https://github.com/Microsoft/AutonomousDrivingCookbook/issues/85)

**Comment by danialvi** [comment]
> 

Hi. How did you solve this. I tried deleting the DistributedRL folder, so it is not overriden the E2Edeeplearning. But still stuck after connection is establish. Please help! Been trying to solve this issue for several weeks
