### ISSUE TITLE
SimMode not valid 

### ISSUE THREAD

**Issue by Benji15150** [microsoft/AirSim#1756]
Hello, 

I am trying to run hello_car.py. However, there is a warning "SimMode Not valid: Car" When I simulate, it correctly spawns the car but when I run the python code, the car stays in place without any action and raises following error: 
![img_8055](https://user-images.githubusercontent.com/30655163/52077425-f63f2e00-255e-11e9-8df1-e658668dd3f9.JPG)
How can I solve this issue? Thank you for your help in advance!

**Comment by msb336** [comment]
@Benji15150
Can you add a comment with your settings.json file to this thread

**Comment by Benji15150** [comment]
`{"SettingsVersion":1.2,
  "SimMode": "Car}`

**Comment by jonyMarino** [comment]
Closed due to age and incompleteness.
Please feel free to open a new issue if you still have this problem, and include the following (as requested when opening a bug issue)

*Make sure to write all reproduction steps
*Include full error message in text form
*Search issues for error message before filing issue
*Attach screenshot if applicable
*Include code to run if applicable

Thanks!
