### ISSUE TITLE
Question: Car to Car distance

### ISSUE THREAD

**Issue by Gaduu** [Microsoft/AirSim#1768]
Quick question regarding distance between 2 vehicles. I'm trying to get an accurate distance, a good and cheap way to do it from my point of view is to get the distance between two vectors, Vector3r.distance_to(self, other) does exactly that. 

My only problem is that the distance varies depending of how you position the cars next to each other. For instance having car_1 and car_2 being next to each other side-by-side gives me the distance of around 3, whereas if the car_1 is facing car_2 in a front-to-front manner it gives the distance of approximately 6 even though in both scenarios the cars are literally crashing into each other. 

Obvious guess is that the origin of the car must be somewhere on a side rather than in the middle of the model. Can any one confirm that? Also, if there a better, more accurate way of estimating the distance?

It is crucial as I don't want my neural net to learn the distance representation incorrectly where in some cases distance of 6 means crash but in other it is 3.

Regards,

**Comment by msb336** [comment]
@Gaduu 
the origin of the car is in the center of the model, but the car is not the same dimensions lengthwise as it is width-wise. Putting them bumper to bumper than yields different centroid distances than putting them next to each other because the centroids are further apart.

For collision detection/avoidance, I would use sensors in the sim to determine true distance from vehicle surfaces
