### ISSUE TITLE
Launching script from within AirSim

### ISSUE THREAD

**Issue by seanny1986** [microsoft/AirSim#1798]
I'd like to use AirSim for RL training, and I've managed to set up a basic gym environment to do what I need (Python 3.5). Ideally, I'd like to be able to run the training algorithm faster than real time; so far, I've figured out how to speed AirSim up using the settings.json file, but the problem is that if I run AirSim and speed it up, the training script is running separately from a terminal at its own speed. If I'm running AirSim at 5x real time, the RL algorithm is still running at the same speed, and is now effectively sending commands to the aircraft 5x slower. 

Is there any way I can launch the training algorithm from within AirSim so that this doesn't happen?

**Comment by seanny1986** [comment]
Bump. Any help here would be greatly appreciated.

**Comment by msb336** [comment]
There is no way to have the training algorithm running inside of airsim without significant modification to the source code.

However, you can scale your RL script update frequency to the accelerated AirSim simulation speed. Obviously, the issue here is that your real time update frequency will be 5x slower than your max possible update frequency on your machine.

For example, if your RL algorithm operates at a max frequency of 20 hz and you have the training setup running at 5x normal speed, you can drop the update frequency to 4 hz when returning to 1x real time in sim.
