### ISSUE TITLE
where to find recorded images and pose?

### ISSUE THREAD

**Issue by gwnudt** [Microsoft/AirSim#181]
I follow the first way to gather the data for training some algorithm by simply pressing the record button on the lower right corner. But I can not find the recored images and poses for training some machine learning algorithms. Where are the  data stored and how we get the images and read poses?

**Comment by saihv** [comment]
They should be stored in C:/Users/<username>/Documents/AirSim.

**Comment by nirmita123** [comment]
![txt](https://user-images.githubusercontent.com/23376276/28208660-7c302206-68ac-11e7-9826-e35feb39927c.JPG)

The recorded images in my case are being stored as a txt file and it's and empty txt(0 bytes) file.
Can someone please suggest a solution?
Thanks a lot

**Comment by saihv** [comment]
Those are not the images, that's the ground truth that's recorded by default along with the images: so the images are not being recorded at all. Did you press 3 in the game window so all the camera views are displayed?

**Comment by nirmita123** [comment]
Thanks @saihv . And yes I pressed 3 for all the camera views but still no difference .

**Comment by nirmita123** [comment]
Thank you so much @saihv . Now , I'm able to get the images in the same folder .

**Comment by nirmita123** [comment]
Also can you please tell me what do these values in the txt file mean?
![val](https://user-images.githubusercontent.com/23376276/28262069-5d67778e-6aff-11e7-8e65-118878516225.JPG)

**Comment by saihv** [comment]
That corresponds to lines 34 to 38 in [RecordingFile.cpp](https://github.com/Microsoft/AirSim/blob/master/Unreal/Plugins/AirSim/Source/Recording/RecordingFile.cpp). Timestamp, position and orientation of the drone.

**Comment by nirmita123** [comment]
Thanks @saihv .It was very helpful.

**Comment by shristi945** [comment]
Hi @saihv   After pressing 3 and recording button in the game window the camera view is obtained but I could not get the large no of images recorded only one single image get recorded and the txt file is still of zero(0 bytes) size and that single image is not as clear as that in the game window camera view. 
Please help.

![capture jpg7](https://user-images.githubusercontent.com/28530708/28510795-dfa8d482-7067-11e7-8478-365e84a88c85.JPG)

the game window view after pressing 3 is like this:

![capture jpg6](https://user-images.githubusercontent.com/28530708/28510859-1b873980-7068-11e7-90c4-8088741bbcdc.JPG)

but the saved image I opened from here  ....\Documents\AirSim\ is like this:

![capture jpg8](https://user-images.githubusercontent.com/28530708/28510986-a6930270-7068-11e7-92bd-6606f3b7ec8e.JPG)

**Comment by shristi945** [comment]
The issue for not getting the number of images and just getting one image instead is resolved. The images got overwritten again and again and only the final image left as output of recording.This is done By changing the code of RecordingFile.cpp
(AirSim/Unreal/Plugins/AirSim/Source/Recording/RecordingFile.cpp) .
By changing the local declaration of imageSavedOk to global only which maintains its value true if the image is saved and hence returning true in if condition so as to get the screenshot saved to . . . log message. Also the txt file of ground truth values do not have 0 byte size.
But the image quality that is being saved is still the same. This problem is not resolved, Please Help.
Thanks in Advance.
