### ISSUE TITLE
Airsim compilation error：

### ISSUE THREAD

**Issue by a11196690** [microsoft/AirSim#1866]
After compiling successfully using build.cmd in Airsim, I get the following error when running the project file. My UE4 version is 4.18, and I downloaded the latest Airsim.
![QQ图片20190402143039](https://user-images.githubusercontent.com/24486910/55380834-0b7f0b80-5554-11e9-8fc7-1352718bd9ee.png)

**Comment by madratman** [comment]
Are you on win 7?

**Comment by lovettchris** [comment]
That seems to be Unreal related, and not an AirSim thing... perhaps related to precompiled header?  Does this discussion help?

https://github.com/20tab/UnrealEnginePython/issues/214

Notice that every header file in the AirSim plugin folder includes this Unreal header first:

```
#include "CoreMinimal.h"
```

Perhaps you added a library that does not abide by this rule.  If so perhaps you should build your library as a lib and include the lib instead of trying to build your library as source code in the unreal project.

**Comment by jonyMarino** [comment]
Please feel free to open a new issue if you still have this problem, and include the following (as requested when opening a bug issue)

*Make sure to write all reproduction steps
*Include full error message in text form
*Search issues for error message before filing issue
*Attach screenshot if applicable
*Include code to run if applicable

Thanks!
