### ISSUE TITLE
could not find function 'getCarState'

### ISSUE THREAD

**Issue by habibutsu** [microsoft/AirSim#1891]
After downloading version `v1.2.0 - Linux/ Blocks.zip` and running following code:

```
client = CarClient()
client.confirmConnection()
client.enableApiControl(True)
client.getCarState()
```

I getting following error

`RPCError: rpclib: server could not find function 'getCarState' with argument count 1.`

**Comment by msb336** [comment]
@habibutsu This is an interesting error. At first try, I am not able to replicate it. Which Linux operating system are you using?

**Comment by habibutsu** [comment]
@msb336  Ubuntu 16.04.4 LTS (GNU/Linux 4.15.0-46-generic x86_64)

**Comment by habibutsu** [comment]
Maybe I can enable debug mode, verbose level for logging or something else for investigate this problem?

**Comment by jonyMarino** [comment]
@habibutsu do you still have this issue with the new airsim version?

**Comment by jonyMarino** [comment]
Closed due to age and incompleteness.
Please feel free to open a new issue if you still have this problem, and include the following (as requested when opening a bug issue)

*Make sure to write all reproduction steps
*Include full error message in text form
*Search issues for error message before filing issue
*Attach screenshot if applicable
*Include code to run if applicable

Thanks!
