### ISSUE TITLE
The imu data is not accurate

### ISSUE THREAD

**Issue by Hezzzzzy** [microsoft/AirSim#1942]
hi folks,
@madratman     I get the imu data by airsim.CarClient().getImuData(),
I recoded a piece of data about acrossing the curve road, then I fit the trajectory by using median integration, compare with the GPS trajectory, has something different

this is the image of the GPS trajectory and imu median integeration trajectory：
[https://photos.app.goo.gl/SWyJAkXuBVteKzis9](https://photos.app.goo.gl/SWyJAkXuBVteKzis9)

**Comment by kylelindgren** [comment]
Link appears to be broken

**Comment by Hezzzzzy** [comment]
> Link appears to be broken

I have tried it, good running...
there are two lines in the image , one GPS trajectory,  the other one is imu trajectory, the imu trajectory has obvious offset

**Comment by Hezzzzzy** [comment]
@kylelindgren  ahaha, this problem has been solved  by an alternative method, get the imu data by speed scalar and orientation, I have checked it , it's no problem

**Comment by jonyMarino** [comment]
Closed due to age.
Please feel free to open a new issue (referring to this one) if you still have this problem, and include the following (as requested when opening a bug issue)

*Make sure to write all reproduction steps
*Include full error message in text form
*Search issues for error message before filing an issue
*Attach a screenshot if applicable
*Include code to run if applicable

Thanks!
