### ISSUE TITLE
Does AirSim for vehicle  have turn signal, hazard light and horn?

### ISSUE THREAD

**Issue by HereIsPatrick** [microsoft/AirSim#1993]
as title.
I'd like to improve autonomous vehicle user experience with car signal.

**Comment by msb336** [comment]
The default vehicle does not have that functionality, but it is definitely something implementable!
The relevant assets for the car can be found [here](https://github.com/microsoft/AirSim/tree/master/Unreal/Plugins/AirSim/Content/VehicleAdv).

In order to reach your goal, you will need to:
1. Add lights and sound to the desired parts of the car
2. Write some blueprints to outline how fast your turn signal should blink, and what call from the API will toggle the turn signal & beep
3. Build new API calls to toggle those functions
