### ISSUE TITLE
The location of the propeller is moved.

### ISSUE THREAD

**Issue by gniwon** [microsoft/AirSim#2029]
I am using my default model(BP_FlyingPawn), and recently I found that the propellers would shift a little after a long flight. What is the problem? Is there solution?

![propeller01](https://user-images.githubusercontent.com/13757890/59813917-54be4a80-934e-11e9-853c-7b4f431e0a60.png)
![propeller02](https://user-images.githubusercontent.com/13757890/59813921-5720a480-934e-11e9-9ced-8b2a3d61630d.png)

8129x8129 size Landscape

**Comment by wuming0624** [comment]
I noticed the same issue. Mine shifted 45 degree after a long run, and started to block my camera. Any fix?

**Comment by jonyMarino** [comment]
Closed due to incompleteness.
Please feel free to open a new issue if you still have this problem, and include the following (as requested when opening a bug issue)

*Make sure to write all reproduction steps
*Include full error message in text form
*Search issues for error message before filing issue
*Attach screenshot if applicable
*Include code to run if applicable

Thanks!
