### ISSUE TITLE
How to set the same color to all cars/buildings... in semantic segmentation images?

### ISSUE THREAD

**Issue by petervlad** [microsoft/AirSim#2035]
![img_0_5_1561219677415599900](https://user-images.githubusercontent.com/32743023/59967415-16818080-9532-11e9-8e0e-8818f7a9ec53.png)

Is it possible to do this from settings.json file?

**Comment by petervlad** [comment]
Found out that you can't. By setting the MeshNamingMethod as "StaticMeshName" in Segmentation Settings the colors will still be different but will be the same and not differ each time you open the environment.

**Comment by YKembal** [comment]
Is this image from the city enviroment ? If yes , can you tell us how did you get this segmented image because when we retrieve the segmented image from airsim it doesn't include the cars and people in the image and i see here that they are detected in your photo.
If you use the segmentation image of airsim please show me your parameters and if not , can you help me find the way of producing this segmented image ?
