### ISSUE TITLE
different metrics measure of airsim and ue4.18.3

### ISSUE THREAD

**Issue by vxgu86** [microsoft/AirSim#2069]
for example, the wall in UE measure is 3meters, but the multi rotor flying over the  wall with y=-2.4xxxx

what is the problem, I searched the issues without colclusion.

**Comment by jonyMarino** [comment]
Closed due to age and incompleteness.
Please feel free to open a new issue if you still have this problem, and include the following (as requested when opening a bug issue)

*Make sure to write all reproduction steps
*Include full error message in text form
*Search issues for error message before filing issue
*Attach screenshot if applicable
*Include code to run if applicable

Thanks!
