### ISSUE TITLE
Latitude, longitude and height

### ISSUE THREAD

**Issue by Rafech** [microsoft/AirSim#2083]
Hi, everyone!
Tell me, is it possible to display on the screen the height, latitude and longitude of my drone?

**Comment by DavidLSmyth** [comment]
You can do this easily enough via the python API using simPrintLogMessage, here are the details: 

simPrintLogMessage: Prints the specified message in the simulator's window. If message_param is also supplied then its printed next to the message and in that case if this API is called with same message value but different message_param again then previous line is overwritten with new line (instead of API creating new line on display). For example, simPrintLogMessage("Iteration: ", to_string(i)) keeps updating same line on display when API is called with different values of i. The valid values of severity parameter is 0 to 3 inclusive that corresponds to different colors.

A separate thread/process that you leave running which connects to the client and every x seconds queries the RAV height, lat, long and then prints to screen with simPrintLogMessage would do the trick I imagine.

You could also dig into the code and implement this on the server side, the UE4 method call is 
GEngine->AddOnScreenDebugMessage(-1, 15.0f, FColor::Yellow, TEXT("Some debug message!"));
