### ISSUE TITLE
How to get values of actors' variables?

### ISSUE THREAD

**Issue by zoubo9034** [microsoft/AirSim#2154]
I want to get information of a traffic light in a downtown environment. How to get its color of light rather than just its position?

**Comment by ironclownfish** [comment]
The traffic light behavior isn't exposed via the AirSim api, since traffic lights aren't a simulator feature. (They're just an object that happens to be in that level)

You'll have to customize AirSim's source code if you want to do this--and probably need to add a little blueprint code to the stoplights in the city environment as well, to expose the light's state.
