### ISSUE TITLE
UE4 sometimes crashes when standalone application is quit

### ISSUE THREAD

**Issue by YumaTheCompanion** [microsoft/AirSim#2182]
My system is Linux, (Ubuntu 18.04) and I've noticed that sometimes UE4 editor crashes when my standalone C++ application (which controls the drone running on UE4 AirSim simulator) is quit by Ctrl+C or of a crash.

This doesn't happen if the stand alone application has entered a loop where all contact with AirSim is stopped, which makes me think when the drone in AirSim receives an uncomplete transmission due to the standalone application crashing, there is an exception either on AirSim or on UE4 side.

**Anyone experience the same issue?**
**Any leads on preventing such behaviour?**

**Comment by jonyMarino** [comment]
Closed due to age and incompleteness.
Please feel free to open a new issue (referring this one) if you still have this problem, and include the following (as requested when opening a bug issue)

*Make sure to write all reproduction steps
*Include full error message in text form
*Search issues for error message before filing issue
*Attach screenshot if applicable
*Include code to run if applicable

Thanks!
