### ISSUE TITLE
Can segmentation image surpport more than 255 objects?

### ISSUE THREAD

**Issue by whatseven** [microsoft/AirSim#2252]
I want to segment every object that appeared in the frame and the num of objects is greater than 255. I tried some solutions but I thought I need some helps or suggestions.

1. I add a ner API `resetIDFromView` and tried to reset the object ID from 1-255 for the objects which can be seen in this frame. But I failed to test the visibility of the objects. I have used these functions to test if the object is visible for the current view;
```
TArray<AActor*> foundActors;
UAirBlueprintLib::FindAllActor<AActor>(simmode_, foundActors);
int object_id = 1;

for (AActor* actor : foundActors) {
            std::string name(TCHAR_TO_UTF8(*(actor->GetName())));
            float deltaTime = actor->GetWorld()->GetTimeSeconds() - actor->GetLastRenderTime();
            bool visible=(deltaTime <= 0.2f) && (deltaTime > 0);
            if (visible) {
                UAirBlueprintLib::SetMeshStencilID(name, object_id, false);
                UE_LOG(LogTemp, Warning, TEXT("%s, %f"),*(actor->GetName()),deltaTime);
                object_id += 1;
            }
        }
```

Since the object besides the view frustum is successfully removed, the object which placed insides the view frustum but occluded still exists in this list. Any idea about that?

2. I'm not sure if this function `GetLastRenderTime` is decided by the exact camera(`e.g. PIPCamera`) or just the viewport. If it is related to the viewport, how can I change it to the specific camera?

3. Do I have any method to make the segmentation support more than 255 objects?

**Comment by ironclownfish** [comment]
Unfortunately segmentation cannot support more than 255 objects, since it uses Unreal Engine's custom stencil buffer with 1 byte per pixel.

Your approach of reassigning IDs on visible objects is probably the best workaround. Unfortunately there is no way to remove occluded objects. You could try sorting the actors in order of distance from the camera, then assign available IDs to only the closest objects. This would not be correct 100% of the time, but it's a bit more likely to cover larger and un-occluded objects.
