### ISSUE TITLE
Gear Values in airsim_rec.txt Does not Indicate Reverse

### ISSUE THREAD

**Issue by damilolah** [microsoft/AirSim#2317]
Hello all,

Please advice. I expect gear values to become negative (-1) when my car goes in reverse while recording but it does not. What can I do about this?
Thanks.

**Comment by jonyMarino** [comment]
Closed due to age.
Please feel free to open a new issue (referring to this one) if you still have this problem, and include the following (as requested when opening a bug issue)

*Make sure to write all reproduction steps
*Include full error message in text form
*Search issues for error message before filing an issue
*Attach a screenshot if applicable
*Include code to run if applicable

Thanks!
