### ISSUE TITLE
vs2017 Failed to start build

### ISSUE THREAD

**Issue by Yannisxm** [microsoft/AirSim#2322]
Failed to start build
错误	MSB3075	命令“"E:\Program Files\Epic Games\UE_4.18\Engine\Build\BatchFiles\Build.bat" LandscapeMountainsEditor Win64 DebugGame "C:\Users\Yanis\Documents\Unreal Projects\LandscapeMountains\LandscapeMountains.uproject" -waitmutex”已退出，代码为 5。请验证您是否拥有运行此命令的足够权限。
![微信图片_20191121234731](https://user-images.githubusercontent.com/40320349/69353327-4daeb600-0cb9-11ea-8043-526af0f11daf.png)

**Comment by jonyMarino** [comment]
Closed due to age and incompleteness.
Please feel free to open a new issue if you still have this problem, and include the following (as requested when opening a bug issue)

*Make sure to write all reproduction steps
*Include full error message in text form
*Search issues for error message before filing issue
*Attach screenshot if applicable
*Include code to run if applicable

Thanks!
