### ISSUE TITLE
Solution for getting object size

### ISSUE THREAD

**Issue by lloydrayner** [microsoft/AirSim#2334]
Hi, 

I am interested in creating a map of objects in the environment. Looking at client.simGetObjectPose() I see object position and wondered if there is a solution to get height and width also?

Thank you

**Comment by ironclownfish** [comment]
We don't currently have plans for an API to return the size of an object's mesh because height/width are inherent properties of objects in the scene that don't really change at runtime. The most straightforward way to get the size would be by opening up the scene in Unreal Engine and taking a look at the meshes. (Assuming you aren't spawning/resizing these objects during runtime)
