### ISSUE TITLE
Settings.json not changing SimMode in Unity

### ISSUE THREAD

**Issue by sbentl02** [microsoft/AirSim#2337]
I am trying to set the SimMode in the settings.json file in Unity. When I run in Unity, there are no errors but no matter what I set SimMode to, it always starts at the selection mode. I have checked that deleting the file produces errors, so it is acknowledging the settings.json file, but doesn't seem to read anything from it.

**Comment by jonyMarino** [comment]
Closed due to age and incompleteness (include setting.json).
Please feel free to open a new issue if you still have this problem, and include the following (as requested when opening a bug issue)

*Make sure to write all reproduction steps
*Include full error message in text form
*Search issues for error message before filing issue
*Attach screenshot if applicable
*Include code to run if applicable

Thanks!
