### ISSUE TITLE
Creating a new vehicle with mass bigger than 3kg

### ISSUE THREAD

**Issue by sebbom** [microsoft/AirSim#2345]
Hello AirSim community,

I am in the process of integrating new vehicles in AirSim but I am wondering if it is actually even possible to have heavier platform.
As stated in: [https://github.com/microsoft/AirSim/blob/0c8dc72ed293ac3fc9445bbc41cec3044fdb523b/AirLib/include/vehicles/multirotor/firmwares/simple_flight/SimpleFlightQuadXParams.hpp#L42 ](https://github.com/microsoft/AirSim/blob/0c8dc72ed293ac3fc9445bbc41cec3044fdb523b/AirLib/include/vehicles/multirotor/firmwares/simple_flight/SimpleFlightQuadXParams.hpp#L42)
it seems that there is a limit in a potential mass, is it only due to the specific simpleflight flight control or because of the physics engine?

I have been trying without success to integrate other flight controller tuned for heavier platform without any success and start to consider that the physics engine is specifically tuned for lighter ones.

Thanks in advance,

**Comment by marcociara379** [comment]
I can confirm the bug, and I think it relates to [my issue #2341](https://github.com/microsoft/AirSim/issues/2341).

**Comment by ibrahim0v** [comment]
@sebbom Hey,
Can you give more details about what you are trying to do? I have integrated my 8kg 35+Nm torque drone with great physical reactions (well, except the collisions and elasticity and stuff like that) but it is working "okay" now

**Comment by jonyMarino** [comment]
Closed due to age and incompleteness.
Please feel free to open a new issue if you still have this problem, and include the following (as requested when opening a bug issue)

*Make sure to write all reproduction steps
*Include full error message in text form
*Search issues for error message before filing issue
*Attach screenshot if applicable
*Include code to run if applicable

Thanks!
