### ISSUE TITLE
AttributeError: 'MultirotorClient' object has no attribute 'moveByRollPitchYawThrottleAsync' 

### ISSUE THREAD

**Issue by khinthandarkyaw98** [microsoft/AirSim#2346]
Error message: 
### AttributeError: 'MultirotorClient' object has no attribute 'moveByRollPitchYawThrottleAsync'

OS : Windows 10
AirSim version : 1.2.5
Python version : 3.6.5
Unreal version : 4.18

AttributeError results when I called the "moveByRollPitchYawThrottleAsync" or "moveByRollPitchYawZAsync" functions. I have updated the airsim library but the error still happens. Could anyone please tell me how to solve this? 

![image](https://user-images.githubusercontent.com/50408474/70891299-5f178380-2015-11ea-8c4d-43bcedc9f84a.png)

**Comment by rajat2004** [comment]
I'm unable to find any API of this name in the entire repo. Could you link to any doc or place where it's mentioned?

**Comment by jonyMarino** [comment]
Closed due to age and incompleteness.
Please feel free to open a new issue if you still have this problem, and include the following (as requested when opening a bug issue)

*Make sure to write all reproduction steps
*Include full error message in text form
*Search issues for error message before filing issue
*Attach screenshot if applicable
*Include code to run if applicable

Thanks!
