### ISSUE TITLE
When the uav lands on the ground, the handle throttle will return to the ground immediately. After the uav rises a little height, the handle will automatically land if it is not operated. What's the matter?

### ISSUE THREAD

**Issue by love-mj** [microsoft/AirSim#2362]
![20191230_095214](https://user-images.githubusercontent.com/37679671/71565616-62b60a80-2aeb-11ea-8e45-79a446e759d4.gif)
How to make him not rebound？

**Comment by saihv** [comment]
What is your landing velocity?

**Comment by love-mj** [comment]
3m/s

**Comment by saihv** [comment]
I would recommend using a lower velocity. Real drones would also exhibit similar behavior if you're landing at 3 m/s

**Comment by love-mj** [comment]
I can see this situation at a very small speed. How can I solve it？

**Comment by jonyMarino** [comment]
Closed due to age and incompleteness.
Please feel free to open a new issue if you still have this problem, and include the following (as requested when opening a bug issue)

*Make sure to write all reproduction steps
*Include full error message in text form
*Search issues for error message before filing issue
*Attach screenshot if applicable
*Include code to run if applicable

Thanks!
