### ISSUE TITLE
The Release doesn't work, and the LOG shows "LogWindows: Failed to load 'aqProf.dll' (GetLastError=126)"

### ISSUE THREAD

**Issue by DinghaoZhang** [microsoft/AirSim#2367]
AirSim is great, but I can't run the Release - "Zhangjiajie" and "SubT". the LOG file shows as following.
``` bash
LogWindows: Failed to load 'aqProf.dll' (GetLastError=126)
LogWindows: File 'aqProf.dll' does not exist
LogWindows: Failed to load 'VtuneApi.dll' (GetLastError=126)
LogWindows: File 'VtuneApi.dll' does not exist
LogWindows: Failed to load 'VtuneApi32e.dll' (GetLastError=126)
LogWindows: File 'VtuneApi32e.dll' does not exist
```
My operation system is Win10, and I use Unreal 4.18.3, VS2017 with "Windows 8.1 SDK".
I try to run it with administrator, but doesn't work.

**Comment by lucaspojo** [comment]
Up ? Same !

**Comment by WLB1996** [comment]
same problem ,did you solve it?

**Comment by jonyMarino** [comment]
Closed due to age.
Please feel free to open a new issue (refering this one) if you still have this problem, and include the following (as requested when opening a bug issue)

*Make sure to write all reproduction steps
*Include full error message in text form
*Search issues for error message before filing issue
*Attach screenshot if applicable
*Include code to run if applicable

Thanks!

**Comment by bkbbq** [comment]
so what the really problem is and how to fix??? have stuff in this case for a few days when running with ue5 git source code . thanks for reply...

**Comment by jonyMarino** [comment]
@bkbbq you can open a new issue, but we don't officially support ue.
