### ISSUE TITLE
need to run the car with only speed parameters but not with throttle.

### ISSUE THREAD

**Issue by surendrasah** [microsoft/AirSim#2462]
Hi,
I have a list of speed values and other signals like accleration, brake, gear and steering value. I would like to test the these signals value and how the car responds. 
I can see that we can send throttle, gear and steering value. I want to set speed value directly to the car but not the throttle. I donot find anything on setting speed value to car but getting speed value.
How can we send manual speed value to the simulator?

**Comment by rajat2004** [comment]
Currently, there's no such API to set the speed of the Car directly. You'll have to modify the code for this, which I think won't be a trivial task since the Car dynamics are not part of AirSim code, and it's implemented in PhysX as throttle-based control. More details can be seen [here](https://docs.unrealengine.com/en-US/API/Plugins/PhysXVehicles/AWheeledVehicle/index.html) and corresponding pages
Another option could be to implement closed-loop control of the speed using the throttle, etc. You can get the current vehicle speed using the API, and adjust the throttle based on that
