### ISSUE TITLE
How to use Hello Drone

### ISSUE THREAD

**Issue by nickylimjj** [Microsoft/AirSim#248]
Hi,

How do I run the sample programs, such as Hello Drone?

I have tried opening `AirSim.sln` but I am not sure how to run the program.

Thank you!

**Comment by Mayankm96** [comment]
Hey! 

You can run the executable file `HelloDrone.exe` directly. It is in the `AirSim/HelloDrone/build/x64/Debug` folder.

**Comment by rovdrcru** [comment]
Hello!

After executing the build.cmd I'm still unable to run the HelloDrone.exe. It seems to be waiting for a good connection.
I wasn't sure if this connection is internet connection since I'm connected with an ethernet-cable.

If not, what should it be connected to? 

![image](https://user-images.githubusercontent.com/57039892/78710969-840e6a00-7916-11ea-9e93-e0390b3f9c68.png)

"c:\Users\Robbe\Documents\AirSim\HelloDrone\build\x64\Debug>HelloDrone.exe
Waiting for connection - XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX..."

**Comment by JBLip** [comment]
That doesn't seem to work for me. When I open the .exe file, the only thing I can see is: 
![image](https://user-images.githubusercontent.com/95872560/145433472-a0ccdf56-9d0f-497e-b8d5-19f33923a5b0.png)

Can anyone please help me?
