### ISSUE TITLE
using pfmpad to check DepthVis floating images is blank

### ISSUE THREAD

**Issue by omarsamyb** [microsoft/AirSim#2543]
Hello, i was trying to check and view a .pfm image of DepthVis that is saved from the airsim recorder but it just gives me a blank screen? like this [https://imgur.com/a/jhUckW6](url)
is it something i should worry about like the file is broken or something? or it is just pfmpad issue?
thank you

**Comment by jonyMarino** [comment]
Closed due to incompleteness.
Please feel free to open a new issue if you still have this problem, and include the following (as requested when opening a bug issue)

*Make sure to write all reproduction steps
*Include full error message in text form
*Search issues for error message before filing issue
*Attach screenshot if applicable
*Include code to run if applicable

Thanks!
