### ISSUE TITLE
How to cross-compile AirSim for LinuxAArch64 platform?

### ISSUE THREAD

**Issue by suchb** [microsoft/AirSim#2611]
Hi,
I am using the LandscapeMountains with AirSim, it's alreay work on window and Linux X64 platform.Package LandscapeMountains without AirSim to LinuxAArch64 is aslo work good, but when I package project with AirSim to LinuxAArch64 platform,I got error from rpc.

**Comment by jonyMarino** [comment]
Closed due to incompleteness.
Please feel free to open a new issue if you still have this problem, and include the following (as requested when opening a bug issue)

*Make sure to write all reproduction steps
*Include full error message in text form
*Search issues for error message before filing issue
*Attach screenshot if applicable
*Include code to run if applicable

Thanks!
