### ISSUE TITLE
Detection does not get detected

### ISSUE THREAD

**Issue by vguillet** [microsoft/AirSim#2654]
I have been using airsim for rl, but often run into issues when training. The collisions are often not reported despite being detected in unreal. Any suggestion?

I am using airsim with python, and use movetopositionto instructions for moving the drone. I tried retrieving the collision information both through  simGetCollisionInfo() and getMultirotorState(). I often end up with the drone ramming into a wall for a while before the situation unlocking itself

**Comment by jonyMarino** [comment]
Closed due to incompleteness.
Please feel free to open a new issue if you still have this problem, and include the following (as requested when opening a bug issue)

*Make sure to write all reproduction steps
*Include full error message in text form
*Search issues for error message before filing issue
*Attach screenshot if applicable
*Include code to run if applicable

Thanks!
