### ISSUE TITLE
import setup_path

### ISSUE THREAD

**Issue by qk-q** [microsoft/AirSim#2797]
when using python API ，it shows unresolved import 'setup_path'.

**Comment by rajat2004** [comment]
`setup_path` is a file in `Pythonclient/multirotor`, etc folders used when the local package is required rather than the pip-installed one. It's only required when making some changes in the airsim Python API. Many of the examples in folders have that since they were added with a new API or something, and `setup_path` is used in those cases.
You can add your new files in those folders, and it'll work, else if the file is somewhere else and no API changes are being made, then just remove the import statement
