### ISSUE TITLE
Fixed wing model

### ISSUE THREAD

**Issue by lyhbuaa** [microsoft/AirSim#285]
How can I add fixed wing models? Has anyone ever done such a thing?

**Comment by lukaszdworako** [comment]
Currently it would require heavy modification, however the best place to start would be to change the rotor_z variable to be based around horizontal flight and find some kind of fixed wing model to import into the plugin, from what I've seen it may not be currently possible however you can still try. Just remember you must also make a new vehicle construction class in order to generate the motors properly and it would also be ideal to change rotor parameters to match that of the fixed wing model.

**Comment by lyhbuaa** [comment]
ok, thank you very much!

**Comment by lyhbuaa** [comment]
ok, thank you very much! @lukaszdworako

**Comment by lukaszdworako** [comment]
@lyhbuaa if you are still trying to modify I accidentally referenced the wrong variable, the correct variable to control thrust direction is unit_z in MultiRotorParams.hpp. If you look through the easiest way to do this would be to create your own vehicle initializer. If more advice feel free to ask.

**Comment by 11tdisast3r** [comment]
I'm also interested to work on adding a fixed wing plane to Airsim

**Comment by RVBldr** [comment]
Internal VSTF 7411.

**Comment by jonyMarino** [comment]
treated in #2955
