### ISSUE TITLE
How does the RCData class work?

### ISSUE THREAD

**Issue by jeffreyng99** [microsoft/AirSim#2860]
Hello, I am trying to write a keyboard operated remote control replacement through the Python API. I've noticed the API offers the moveByRC function. Within it there is the RCData object that I pass in. What does each of the member variable's data represent? Is there a more in-depth documentation/example about this class?

System settings:
Ubuntu 18.04
Python 3.6.9
AirSim 1.3.1
Unreal 4.24.3

Here is the RCData class:
```python
class RCData(MsgpackMixin):
    timestamp = 0
    pitch, roll, throttle, yaw = (0.0,)*4 #init 4 variable to 0.0
    switch1, switch2, switch3, switch4 = (0,)*4
    switch5, switch6, switch7, switch8 = (0,)*4
    is_initialized = False
    is_valid = False
    def __init__(self, timestamp = 0, pitch = 0.0, roll = 0.0, throttle = 0.0, yaw = 0.0, switch1 = 0,
                 switch2 = 0, switch3 = 0, switch4 = 0, switch5 = 0, switch6 = 0, switch7 = 0, switch8 = 0, is_initialized = False, is_valid = False):
        self.timestamp = timestamp
        self.pitch = pitch
        self.roll = roll
        self.throttle = throttle
        self.yaw = yaw
        self.switch1 = switch1
        self.switch2 = switch2
        self.switch3 = switch3
        self.switch4 = switch4
        self.switch5 = switch5
        self.switch6 = switch6
        self.switch7 = switch7
        self.switch8 = switch8
        self.is_initialized = is_initialized
        self.is_valid = is_valid
```

**Comment by madratman** [comment]
There's an example script here https://github.com/microsoft/AirSim/blob/123bbd6d6416bbe98e775101ba8ebcb5ccbf8501/PythonClient/multirotor/manual_mode_demo.py

The main params to care about are the RPYThrottle, and the values of switch1 and switch2. 
switch1 decides if RPY values are interpreted as angle level set point or angle rate setpoints. 
Itis implemented as a "3-way switch", which however only allows 2 interpretations of the RPY commands you send. 
If the value of switch1 is less than 0.3, the commands are interpreted in angle mode. Else, in body rate mode. 

switch2 determines if API control is enabled or not
If the value of switch2 is greater than 0.1, API control is enabled. 
 
The RCData params set by "moveByRC" get consumed by the flight controller's offboardapi in these lines https://github.com/microsoft/AirSim/blob/c340b7653efd22cefe2ae3f9110daf87d3fc6ae9/AirLib/include/vehicles/multirotor/firmwares/simple_flight/SimpleFlightApi.hpp#L115-#L138
while RPYThrottle are clear enough, we can see something is going on wrt the switches / channels behind the scenes (which will also change how the params are interpreted - RPY angle setpoint values of RPY anglerate setpoint values)  

In the flight controller's update loop, we listen to the RCData's goal value and goal mode via the `updateGoalFromRc` function -  https://github.com/microsoft/AirSim/blob/c340b7653efd22cefe2ae3f9110daf87d3fc6ae9/AirLib/include/vehicles/multirotor/firmwares/simple_flight/firmware/OffboardApi.hpp#L38-#L63 

You can see the 3-way switch in these lines - https://github.com/microsoft/AirSim/blob/c340b7653efd22cefe2ae3f9110daf87d3fc6ae9/AirLib/include/vehicles/multirotor/firmwares/simple_flight/firmware/RemoteControl.hpp#L175-#L181
The 0.3 value is set here https://github.com/microsoft/AirSim/blob/7d398add700ce4ba9ebe150dffabd9267f77a0f2/AirLib/include/vehicles/multirotor/firmwares/simple_flight/firmware/Params.hpp#L41

P.S. I also think this line is wrong https://github.com/microsoft/AirSim/blob/c340b7653efd22cefe2ae3f9110daf87d3fc6ae9/AirLib/include/vehicles/multirotor/firmwares/simple_flight/firmware/RemoteControl.hpp#L208. 
It should use `angle_rate_pid.max_limit)` instead of `angle_level_pid`

The 2nd switch is being read here https://github.com/microsoft/AirSim/blob/c340b7653efd22cefe2ae3f9110daf87d3fc6ae9/AirLib/include/vehicles/multirotor/firmwares/simple_flight/firmware/RemoteControl.hpp#L191
