### ISSUE TITLE
Mac OS build error: Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by cnpcshangbo** [microsoft/AirSim#2952]
This error appears during the build process.
'''
[100%] Linking CXX executable ../output/bin/AirLibUnitTests
Undefined symbols for architecture x86_64:
  "___darwin_check_fd_set_overflow", referenced from:
      mavlinkcom_impl::UdpSocketImpl::recv(void*, unsigned long, unsigned int) in libMavLinkCom.a(UdpSocketImpl.cpp.o)
      mavlinkcom_impl::UdpSocketImpl::pollin(unsigned int) in libMavLinkCom.a(UdpSocketImpl.cpp.o)
      mavlinkcom_impl::UdpSocketImpl::pollout(unsigned int) in libMavLinkCom.a(UdpSocketImpl.cpp.o)
ld: symbol(s) not found for architecture x86_64
clang-8: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [output/bin/AirLibUnitTests] Error 1
make[1]: *** [AirLibUnitTests/CMakeFiles/AirLibUnitTests.dir/all] Error 2
make: *** [all] Error 2
'''
![image](https://user-images.githubusercontent.com/4831029/90683799-bfa63280-e22c-11ea-86b4-938a26f6bc1a.png)

**Comment by rajat2004** [comment]
This has been extensively discussed in #2559, so better to continue there itself
Essentially, it's a problem in XCode 11.4, seems to be fixed in 11.4.1 but is present in 11.5 as well, so not completely sure which versions are affected.
You could comment out the lines causing the problem, they're only relevant if using AirSim with ArduPilot. See https://github.com/microsoft/AirSim/issues/2559#issuecomment-615021972 and below for more details
