### ISSUE TITLE
Access violation when specifiying json settings

### ISSUE THREAD

**Issue by mape1082** [Microsoft/AirSim#30]
Hi, 
Since I don't have the physical RC, I am trying to use the firmware in Ubuntu guest, on host windows 10.

In Ubuntu I get:
INFO  [simulator] Waiting for initial data on UDP port 14560. Please start the flight simulator to proceed..

Therefore I try running the simulation in W10. Assign the game mode to SimGameMode, then Play button and then I get an access violation in  

>	UE4Editor-AirSim.dll!mavlinkcom::MavLinkConnection::join(std::shared_ptr<mavlinkcom::MavLinkConnection> remote, bool) Line 109	C++

settings.jason: (as specified in the readmes:
`{
  "AirControlCompID": 1,
  "AirControlSysID": 134,
  "ExtRendererCompID": 1,
  "ExtRendererSysID": 167,
  "ExternalSimPort": 14588,
  "LocalHostIp": "127.0.0.1",
  "LogViewerHostIp": "127.0.0.1",
  "LogViewerPort": 14388,
  "Pixhawk": {
    "SerialBaudRate": 115200,
    "SerialPort": "*",
    "UdpIp": "127.0.0.1",
    "UdpPort": 14560,
    "UseSerial": true
  },
  "QgcHostIp": "127.0.0.1",
  "QgcPort": 14550,
  "SimCompID": 42,
  "SimSysID": 142
}`

In UdpIp, instead of 127.0.0.1, i am using the real ip address of my Ubuntu VM.

When I don't specify json file, it goes ok, but it wont connect to PX4 on Ubuntu. If I specify json settings, it seems so far no matter what, it will crash.

Any ideas?

Thanks and regards.

**Comment by lovettchris** [comment]
I just checked in [this fix](https://github.com/Microsoft/AirSim/commit/3a2f045d57bd228b9aa59eeba1dc2f9ccf0e8b5d).

If you want to run the above posix_sitl in a VirtualBox Ubuntu machine then it will have a different ip address from localhost. So in this case you need to do the following: 1. Run the sitl so it is "listening", you should see the message INFO [simulator] Waiting for initial data on UDP port 14560 2. Edit the settings file so that the UseSerial is false, the UdpIp address is the ip address of your virtual machine and the LocalIpAddress is the address of your host machine running the Unreal engine.

**Comment by mape1082** [comment]
Thanks a lot.
