### ISSUE TITLE
Can I use API to get images every frame in the game?

### ISSUE THREAD

**Issue by c6376315qqso** [microsoft/AirSim#3025]
I fixed my game frame rate to 30 fps.
Now I want to get images (depth map or segmentation or whatever) using python API in every frame, Is this achievable?

**Comment by GimpelZhang** [comment]
From my point of view, 30 Hz of images capture is quite a high demand on your hardware.

**Comment by c6376315qqso** [comment]
> From my point of view, 30 Hz of images capture is quite a high demand on your hardware.

Yeah,it is. But I want to know how to achieve getting images every frame?

**Comment by ivannson** [comment]
I think the speed with which you are getting images depends on your hardware, you can time the process to determine the camera frame rate. If you strictly need it every frame, rather than just as quickly as possible, then you can set fixed frame rate within the Editor settings. 

What I mean is this:
Suppose it takes 0.1 seconds to get an image using the Python API, so your recording frame rate is 10 fps, whereas your simulation is running at 30 fps. I'm not sure you can speed the process up and obtain images quicker than 10 fps as it's limited by the hardware, but you can decrease the editor frame rate to 10 fps, so you are getting images every frame.

That said, I'm not sure why exactly you'd want to do that. As opposed to Lidar, I wouldn't think it really matters if the images are collected every other frame.

**Comment by c6376315qqso** [comment]
> I think the speed with which you are getting images depends on your hardware, you can time the process to determine the camera frame rate. If you strictly need it every frame, rather than just as quickly as possible, then you can set fixed frame rate within the Editor settings.
> 
> What I mean is this:
> Suppose it takes 0.1 seconds to get an image using the Python API, so your recording frame rate is 10 fps, whereas your simulation is running at 30 fps. I'm not sure you can speed the process up and obtain images quicker than 10 fps as it's limited by the hardware, but you can decrease the editor frame rate to 10 fps, so you are getting images every frame.
> 
> That said, I'm not sure why exactly you'd want to do that. As opposed to Lidar, I wouldn't think it really matters if the images are collected every other frame.

Emmm,I need to synchronize sampling in airsim with the tick function in ue4, Because I

**Comment by c6376315qqso** [comment]
> I think the speed with which you are getting images depends on your hardware, you can time the process to determine the camera frame rate. If you strictly need it every frame, rather than just as quickly as possible, then you can set fixed frame rate within the Editor settings.
> 
> What I mean is this:
> Suppose it takes 0.1 seconds to get an image using the Python API, so your recording frame rate is 10 fps, whereas your simulation is running at 30 fps. I'm not sure you can speed the process up and obtain images quicker than 10 fps as it's limited by the hardware, but you can decrease the editor frame rate to 10 fps, so you are getting images every frame.
> 
> That said, I'm not sure why exactly you'd want to do that. As opposed to Lidar, I wouldn't think it really matters if the images are collected every other frame.

Because I also get positions in tick function in ue4, so I want to exactly get images every tick, is this achievable?

**Comment by niekvleeuwen** [comment]
I also looked at the possibility of receiving images every frame. I added an extra feature to AirSim for this purpose, see the pull request [here](https://github.com/microsoft/AirSim/pull/3102). Maybe you can take a look.
