### ISSUE TITLE
AirSim build error on Windows 10 -> AirLib.lib error LNK2001, LNK2019, LNK1120

### ISSUE THREAD

**Issue by rmolinabadia** [microsoft/AirSim#3030]
Hi everyone,

I'm trying to build AirSim on my computer:
- Windows 10.
- Visual Studio 2019, with Desktop Development with C++ and Windows 10 SDK 10.0.18362.
- AirSim v1.3.1.
- Unreal Engine 4.25.

I've followed the building instructions as stated in [https://microsoft.github.io/AirSim/build_windows/], but I do get an error after running the 'build.cmd' command. The issue comes from the AirLib.lib library, throwing LNK2001, LNK2019 and LNK1120 errors.

The attached image includes the entire output of the 'build.cmd'. Errors can be seen aprox. from the 3/4 onwards.

Steps to build AirSim are quite simple, but I don't get to understand why am I getting these errors every time I try to build it. Could anyone please help me?

Thanks in advance,
rmolinabadia

![AirSim build error on Windows 10](https://user-images.githubusercontent.com/67288026/93711344-ca1a5b80-fb4d-11ea-9ac3-a8f9966b44c0.png)

**Comment by rajat2004** [comment]
Not sure what's happening, the command prompt also is correct otherwise that could have been causing the erorrs. Maybe run `clean.cmd` or `clean_rebuild.bat` once and try again
The CMake version seems a bit stragne, I'm using 3.16, the 3.14 one seems somewhat old, was that installed separately earlier? Even the latest 3.14 version is 3.14.7

**Comment by rmolinabadia** [comment]
Hi @rajat2004 ,

As you said, CMake version update to 3.16.9 did the job.

Thanks for your fast reply and your help!
