### ISSUE TITLE
Invalid uncomressed images when recording from Unreal editor

### ISSUE THREAD

**Issue by alonfaraj** [microsoft/AirSim#3214]
## Bug report 

- AirSim Version/#commit: 1.3.1
- UE/Unity version: 4.25.4
- autopilot version: N/A
- OS Version: Win10

### What's the issue you encountered?

Recording uncompressed images from Unreal editor using rec button, output invalid images which can't be open when set `"Compress": false`. 
When record compress images - it works fine.

![Capture](https://user-images.githubusercontent.com/15960497/102071452-29180580-3e09-11eb-9bd1-0e12bfd4e244.PNG)

### Settings

Example:
```
  "Recording": {
    "RecordOnMove": false,
    "RecordInterval": 1,
    "Cameras": [
        { "CameraName": "0", "ImageType": 0, "PixelsAsFloat": false, "Compress": false },
        { "CameraName": "0", "ImageType": 5, "PixelsAsFloat": false, "Compress": false }
    ]
  }

```
### How can the issue be reproduced?

1. Add uncompress camera to recording section in setting file
2. Record from unreal editor using 'R'
3. Check the images folder

**Comment by rajat2004** [comment]
This is a known bug, mentioned here - https://github.com/microsoft/AirSim/pull/2861#issuecomment-664036371
Copied from the above linked comment - UE is doing the conversion to PNG format, and then we're just writing it as a binary file. For uncompressed, writing array values as binary doesn't work. I can see 2 options, either go for an external library such as `libpng` which will do the conversion and all (format's complex, so doesn't seem to be possible to write it ourselves), or use a different format such as PPM which is simpler and can be written similar to how PFM file is being written currently.
I haven't worked on it more since then, maybe will pick it up again, I guess PPM will be better than nothing, external libraries are somewhat painful to inlcude, especially for cross-platform.

**Comment by alonfaraj** [comment]
thank you @rajat2004
