### ISSUE TITLE
losing altitude when yawing

### ISSUE THREAD

**Issue by abdelrahman-t** [Microsoft/AirSim#324]
Is there a way to enable altitude hold mode through sitl or any otherway while in offBoard mode as i found out tham am losing quite a bit of altitude when yawing, which eventually causes unintentional landing!

i have been going through px4 dev guide to find a solution but to no avail, has any one here tried this ?

thanks

**Comment by lovettchris** [comment]
We use "moveByVelocityZ" for this purpose.  But this is currently not an option for moveByAttitude.  Or are you using rotate methods?  You could rotate using moveByVelocityZ by passing different YawModes.

Turns out that real drones lose altitude when yawing counter clockwise, and gain altitude when yawing clockwise, so if the simulator is doing that then it is being ultra realistic :-)

**Comment by abdelrahman-t** [comment]
i see, simulator is pretty realistic, i was pulling my hair out, because my reinforcement agent kept doing these unintentional landings instead of yawing.

that's pretty interesting,

thank you chris 😄

**Comment by abdelrahman-t** [comment]
on the same not, i was wondering, is there a way to always force the quadcopter to move with camera always pointing in the direction of movment , instead of yawing whilst moving in forwardOnly mode

**Comment by sytelus** [comment]
@abdelrahman-t forwardonly mode allows movement only in forward direction.  Please start new issue if that's not what you want.
