### ISSUE TITLE
Adding a sensor to a VehicleType of ArduPilot causes it not to work

### ISSUE THREAD

**Issue by MoBaT** [microsoft/AirSim#3279]
## Bug report 

- AirSim Version/#commit: v1.3.1-linux
- Unreal map: https://github.com/microsoft/AirSim/releases/download/v1.3.1-linux/Blocks.zip
- UE/Unity version: 4.25.1-0+++UE4+Release-4.25 518 0
- autopilot version: 2763ce0
- OS Version: Ubuntu 18.04

### What's the issue you encountered?

![image](https://user-images.githubusercontent.com/648536/103800310-df8a9700-5011-11eb-94db-3081e5f111a0.png)

### Settings

https://gist.github.com/MoBaT/4dc5d1c2a836ee489820e7d6cb2e5a81

### How can the issue be reproduced?

1. Add a "Sensors" block and add any type of sensor to it. In my case I added a Lidar (6)

**Comment by rajat2004** [comment]
This is occurring due to the GPS and IMU sensors not being present in the settings, they are required for AP to work, see the settings on this page - https://ardupilot.org/dev/docs/sitl-with-airsim.html#using-lidar

If the `Sensors` block is present in the settings, only the specified sensors will be created since AirSim allows creating vehicles without any sensors as well. There's some discussion which can be done as to ensure the minimum sensors required for the specific vehicle are always present, something like `DefaultSensors: true` maybe.

**Comment by MoBaT** [comment]
@rajat2004 Thanks for this info! This worked for me. I was under the assumption that IMU's and GPS would be on there by default.
