### ISSUE TITLE
Version attribute for python airsim package

### ISSUE THREAD

**Issue by jonyMarino** [microsoft/AirSim#3634]
### Overview:

the idea is to be able to run something like this:
```
import airsim
print (airsim .__ version__)
```
and get a string like `1.5.0`

### Nature of Request:  

- Addition

## Why would this feature be useful?
This will allow you to know which version of AirSim is being used.

**Comment by saihv** [comment]
Just FYI, if anyone needs this functionality before this is implemented: `pip show airsim` also displays the version info.

**Comment by rajat2004** [comment]
Just commenting here since package versioning is being discussed, the [setup.py](https://github.com/microsoft/AirSim/blob/master/PythonClient/setup.py#L8) shows the version as `1.2.8` but the latest version on [PyPI](https://pypi.org/project/airsim/) is `1.3.0`. Another doubt I have is that shouldn't there be a new Python package release for each Airsim release as well? As in there's no package for 1.4.0

**Comment by jonyMarino** [comment]
Yes. That would be ideal. Let me ask how I need to proceed.
The package in PyPI returns version `1.2.8`, correct?

**Comment by jonyMarino** [comment]
The airsim pip package was updated.
As Sai pointed out, `pip show airsim` is enough. Closing this.
