### ISSUE TITLE
How to change idle thruttle?

### ISSUE THREAD

**Issue by EdwinMeriaux** [microsoft/AirSim#3819]
So from this document:
https://github.com/microsoft/AirSim/blob/master/AirLib/include/vehicles/multirotor/MultiRotorParams.hpp

It says Idle thruttle for simple flight is 50%. Is there any what to change that?

**Comment by EdwinMeriaux** [comment]
the drone that I would like to simulate has a particular max thrust and the drone's idle is lower than 50% max thrust. Is there any way to change this?

**Comment by rajat2004** [comment]
@ahmed-elsaharti might have a better idea regarding this, referring to his PR https://github.com/microsoft/AirSim/pull/3401

**Comment by ahmed-elsaharti** [comment]
Hey guys, 
If I remember correctly, the 50% idle thrust (I'm assuming we're talking about the simpleflight flight controller here) in my case was set by the gamepad/joystick connected to the computer via USB. ie: since i was using a USB gamepad with thumbsticks that default to the center, it pushed out a signal of 50% (ie: center). I remember the idle throttle dropping below 50% once no joysticks were connected to the computer.

Idr exactly where the non-joystick idle throttle was set but I'd assume it would be somewhere in the simpleflight directory since that parameter should be controlled by the autopilot code.

**Comment by EdwinMeriaux** [comment]
Hello!

Wait so this idle rate still holds when programming the drones with Python instead of flying with joystick?

**Comment by EdwinMeriaux** [comment]
@ahmed-elsaharti
