### ISSUE TITLE
moveonpath lookahead and the 'z' cordinate problems

### ISSUE THREAD

**Issue by fmzhu** [Microsoft/AirSim#439]
hello,

I make the  Drone to move on a path, sometimes it just stopped and returns back in the middle when it didn't reach the destination. But sometimes it finished the task normally. So should I pay attention to the ''lookahead'' and the ''Velocity'', what's the relationship between the two parameters? And when I set the parameters of 'z' in minus, the drone flies in the normal situation., but the opposite way didn't work. The 'z' parameter in my unreal environment is always more than 0. 

Thank you very much for your help!

**Comment by sytelus** [comment]
Unreal use NEU coordinates while AirSim and most other infrastructures like ROS uses NED coordinates (i.e. North-East-Down, i.e. down is +ve, up is -ve).
Generally you can just set look_ahead = -1 which means "auto mode". It usually does good job given constraints. If velocity is too high then you will see some oscillations because its simple carrot following algorithm. There is one other way to tune this behaviour using 
`safety_params_.vel_to_breaking_dist' and `safety_params_.min_breaking_dist` but they haven't been exposed in settings or through API yet.
