### ISSUE TITLE
UE4 16 crashes with the newest airsim

### ISSUE THREAD

**Issue by lxgen** [Microsoft/AirSim#452]
When I start the ue4 project, and type a command like takeoff in droneshell. UE4 will crash suddenly. What's wrong with it? I have run the older version successfully.

**Comment by sytelus** [comment]
With new flight controller, you will need to first do requestControl command before you make any other API call. This is safety feature in many drone APIs including simple_flight which is default in AirSim as well as DJI APIs, for example,

The crash was happening because of DebugBreak() statement, however. I'd assumed those statement would be no-op in binary release but they aren't and causes the crash. In latest source I've removed those statement so you would see a message indicating that you must use "requestControl" first before you arm.

So in DroneShell, you do following sequence:

requestControl
arm
takeoff
