### ISSUE TITLE
How i can connect by Xbox joystick to PC directly.

### ISSUE THREAD

**Issue by zf223669** [Microsoft/AirSim#49]
I have no Pixhawk firmware, is it possible to control the vehicle by the XBox joystick which connected to PC directly?
I plugin the xbox joystick to the PC USB port, but the QGroundController did not detected it.

**Comment by sytelus** [comment]
It is possible but it's hard to set it up. I got it working once but the problem was that joystick is not high precision device like RC and so it was very hard to control the drone (joystick controls seem to have lot of noise). There few tips in [this doc](https://github.com/Microsoft/AirSim/blob/master/docs/sitl.md) (see last section). If this works for you, please feel free to update the doc :).

Also, we are preparing new feature which will eliminate need for RC as well as PX4. It probably won't be as realistic however it should be good enough - at least better than nothing. We expect to release this new version in 2-3 weeks.
