### ISSUE TITLE
How to Use Programmatic control?

### ISSUE THREAD

**Issue by zhongtao93** [Microsoft/AirSim#51]
Is there a usage in more details about how to use programmatic control?
I build HelloDrone and run it, A shell appears and  shows that "Press Enter to arm the drone ", then how to connect the Unreal Project. 
 After reading https://github.com/Microsoft/AirSim/blob/master/docs/apis.md I still feel confused to use it.

Thank you!

**Comment by lovettchris** [comment]
We have some limitations to watch out for that we are working on improving, but for now:
1) The Unreal Project needs to be running (Click Play) before you try and connect the HelloDrone app.
2) There is a bug such that if you "Stop" the unreal project you have to stop the UE Editor and restart it, otherwise the server will not reconnect to the Drone client api.  

These are rpclib limitations/bugs and we plan to fix them, just don't have it in yet...  

If you want to dig deeper the RpcLibServer is running in the Unreal project if you have added the Plugin correctly.  Then any other process can connect to that server using RpcLibClient.  These communicate over TCP.  Note that both RpcLibClient and RpcLibServer can also take ip addresses, and this enables RPC over the network instead of on the same machine.  But of course if you do it over the network you need to also worry about any firewalls, so you may need to open the default RpcLibClient port of 41451.

**Comment by sytelus** [comment]
Hi @zhongtao93, just to add on...

@lovettchris had posted video on how to use DroneShell. Here's the segment that goes over DroneShell: https://youtu.be/HNWdYrtw3f0?t=510

DroneShell is just more featureful version of HelloDrone. As Chris mentioned above, first run Unreal project. Make sure you are able to take off drone manually with RC and fly it around so you know everything is working. Then stop editor and start again. Run HelloDrone and execute commands there. Currently we have commands like takeoff, land, moveToPosition, moveByVelocity working. For other commands we have found one bug that we are working on fix in coming few days.

**Comment by zhongtao93** [comment]
Thank you for your answer!
Hi, @sytelus, do I must have a RC to connect it before programmatic control? I run Unreal project and it shows as below:
![qq 20170226134643](https://cloud.githubusercontent.com/assets/15263824/23337484/2de50182-fc2a-11e6-9e17-659664987df0.png)

Thank you.

**Comment by sytelus** [comment]
You do need PX4 in hardware-in-loop or software-in-loop. One other problem is that PX4 might not allow you to fly if you don't have RC because in real life it would be unsafe because there is no possibility of manual override or kill switch. I haven't tested this so just my guess.

In next week or two, we plan to release Standalone Mode which will allow you to use AirSim without PX4. In this mode, you should be able to use API without RC or any additional harddware. However XBox or other game pad might still be required for manual flight.

**Comment by zhongtao93** [comment]
OK, thank you very much. I'm look forward to the next release

**Comment by udaydlsv** [comment]
Do we have the standalone mode yet ? I do not have any additional hardware and tried to control the drone with droneshell. I get the following error. Is this expected ? 
![error_airsim](https://cloud.githubusercontent.com/assets/26799751/24623602/d3f54808-185d-11e7-8ee6-817452a58cd6.PNG)

**Comment by lovettchris** [comment]
standalone is still in development.  But you can use [sitl mode](https://github.com/Microsoft/AirSim/blob/master/docs/sitl.md) without any additional hardware.

**Comment by pdebitetto-tft** [comment]
Hi Chris, the link to SITL mode does not work.  did the functionality go away?  
Thanks
Paul

**Comment by delphifissure** [comment]
Here's a +1 for SITL mode, is that gone? Would love to be able to test programmatic flight control with physics before I pull the trigger on drone hardware.

Thanks!

**Comment by vinbo** [comment]
I found it too...
