### ISSUE TITLE
DroneShell rpc::timeout

### ISSUE THREAD

**Issue by exploke** [microsoft/AirSim#523]
I am attempting to get images of an area in a 360 view using DroneShell. The command I am using is _**==||=> circlebypath -radius 15 -drivetrain 1 -yaw 90 -velocity 1 -z -5**_ but I eventually keep getting the error **_==||=> Error occurred: rpc::timeout: Timeout of 60000ms while calling RPC function 'moveOnPath'_** after the drone starts circling around the area. Is there anyway to fix this timeout issue?

**Comment by jonyMarino** [comment]
Closed due to age and incompleteness.
Please feel free to open a new issue if you still have this problem, and include the following (as requested when opening a bug issue)

*Make sure to write all reproduction steps
*Include full error message in text form
*Search issues for error message before filing issue
*Attach screenshot if applicable
*Include code to run if applicable

Thanks!

**Comment by lknnnli** [comment]
> I am attempting to get images of an area in a 360 view using DroneShell. The command I am using is _**==||=> circlebypath -radius 15 -drivetrain 1 -yaw 90 -velocity 1 -z -5**_ but I eventually keep getting the error **_==||=> Error occurred: rpc::timeout: Timeout of 60000ms while calling RPC function 'moveOnPath'_** after the drone starts circling around the area. Is there anyway to fix this timeout issue?

hi, have you solved this problem?

**Comment by sandilyasg** [comment]
@exploke @lknnnli were you able to solve this problem?
