### ISSUE TITLE
Camera_view: Scene shows back view

### ISSUE THREAD

**Issue by Kjell-K** [Microsoft/AirSim#533]
The camera index 3 with scene as default show the back view since the last update in the Unreal window.

**Comment by sytelus** [comment]
We recently changed the scene view to rear camera (instead of front) to show off the multi-camera capabilities. But looks like this is throwing off many people so I would revert it back to front camera in next release. Meanwhile, if you had like to change this just add following in your [settings.json](https://github.com/Microsoft/AirSim/blob/master/docs/settings.md):

"SubWindows": [
    {"WindowID": 2, "ImageType": 0, "CameraID": 0, "Visible": true}
  ]

**Comment by raymondchua** [comment]
Thanks @sytelus for the info!
