### ISSUE TITLE
MAVLink V2 does not work

### ISSUE THREAD

**Issue by zergler** [microsoft/AirSim#546]
When trying out the PX4 HIL mode on Ubuntu 16.04 using a Pixhawk (1.5.5), I was not able to takeoff because of message length mismatches. Although, some commands like arming/disarming seemed to work.

![image](https://user-images.githubusercontent.com/1537790/31682162-4bf24728-b347-11e7-90ea-bd82b92abefe.png)

Changing the MAV_PROTO_VER parameter in QGC to "Always use version 1" fixed these errors.

**Comment by sytelus** [comment]
@lovettchris might be interested in this.

**Comment by willluer** [comment]
Any update on this? I'm having the same issue now

**Comment by jonyMarino** [comment]
Closed due to age and incompleteness.
Please feel free to open a new issue if you still have this problem, and include the following (as requested when opening a bug issue)

*Make sure to write all reproduction steps
*Include full error message in text form
*Search issues for error message before filing issue
*Attach screenshot if applicable
*Include code to run if applicable

Thanks!
