### ISSUE TITLE
Focus on target

### ISSUE THREAD

**Issue by oppne** [Microsoft/AirSim#564]
How can i make the drone fly to, avoid obstacles and focus on a target?
I want it to circle around as well, having a hard timr finding this out

**Comment by kaihuchen** [comment]
@oppne   You may reference my project [here](https://github.com/kaihuchen/DRL-AutonomousVehicles) which deals with obstacle avoidance based on DRL (deep reinforcement learning)

I am also considering adding the feature of targeted travel as follows:

1. Make the target visible to the given sensors in some fashion. If you want it to work for a target that is not directly visible then you can cheat a little by providing a target sensor indicating the direction of the drone in some way. 
1. Update the DRL reward function so that the drone is rewarded for getting closer to the target.  

If the rewards and penalties are set up properly, I think there is a good chance that the drone can eventually learn to fly towards the target while avoiding obstacles at the same time.

**Comment by oppne** [comment]
Sounds interesting! Is this working for ue4.16? 
Targets are most important, as this is gonna be to recognize objects, i want to try to make the drone compatible with blueprints, as of i wanted to make actors that are the object with collision, when the drone overlaps, i was thinking about triggering an event that makes the drone circle around the actor focusing the camera on the object, but i am unsure how to proceed

**Comment by kaihuchen** [comment]
I do not entirely understand your description above, but if you want the drone to circle around the target with the camera pointing to it, then perhaps it can achieved by:

1. Rewarding the drone for keeping the target in sight
1. Penalize the drone for getting too close (so as to keep it at a constant distance when it gets closer)
1. Penalize the drone for hovering when it gets close to the target (so as to prevent it from hovering motionless without circling).

It will take some experiments to verify how well DRL works out for the above. It might also be worthwhile to check out [Hierarchical RL](https://blog.openai.com/learning-a-hierarchy/) for this.

**Comment by oppne** [comment]
Yes ofcourse, but this is in the future to develope.

The one thing i want now is this:
I want the drone to fly in a spesific path.
When the drone is at a certain point, i want the drone to circle around this object.

For example i have a spesific tree with blueprints on it.
The tree is a special tree.
When this drone flies near this tree, i want it to trigger an event.
This event triggers that the drone should fly around this object and take pictures from many different angles.
After some time it finishes taking picture and then continues on his path.

**Comment by oppne** [comment]
at the same time i cant seem to change the recording settings either. When i try to change the json file in the documents, the pictures still comes out as standard.

**Comment by kaihuchen** [comment]
Ah, I see. FYI, my interest is in enabling a drone/car to learn how to execute highly complex task all by itself. I have no interest in manually writing code to control a drone directly.  Maybe somebody can help you with that.

**Comment by oppne** [comment]
aww to bad, i wanted to use this code to make a pattern for AI.

Now i currently want to make blueprint nodes that are compatiable with airsim, i will get back at you on my process
