### ISSUE TITLE
Blueprints API call - Timeout

### ISSUE THREAD

**Issue by oppne** [Microsoft/AirSim#606]
Hey guys, We have developed a new way to access the API, but im having one issue that prevents it from working.

Currently now, the API is exposed to blueprints, and attached to an actor that is being placed in the world.
The actor has nodes, that include around 20 command nodes, with arm, request api controll, enter hover mode, takeoff.

All of these should work.
The request control works, arm the drone works, everything works but the moving nodes. 
Lets take the takeoff node.

![image](https://user-images.githubusercontent.com/22558756/32632439-f090059a-c5a3-11e7-9a66-11d1eeb75494.png)

when triggered, this will trigger a bug , that freezes the game, for about 10 seconds, then theres a debug note that comes in the top left corner, saying "API call timed out, entering hover mode", but the drone has switched place to the takeoff height.

Does anybody know where we can start to fix this issue?

**Comment by sytelus** [comment]
Looks like this is same as https://github.com/Microsoft/AirSim/issues/608

The reason this is happening because you are making BP call from the game thread. The takeoff is long running operation so your call doesn't return for quite some time and game thread remains blocked which causes freeze. To work around this try spawning new thread and making a call from that thread so game thread doesn't get blocked.
