### ISSUE TITLE
using flight api from within ue4

### ISSUE THREAD

**Issue by laggyluk** [Microsoft/AirSim#608]
Hi
We are trying to control the drone from ue4 blueprint via flying API.
What I did is I've created an actor that exposes msr::airlib::MultirotorRpcLibClient methods to BP. It works to some extent, drone can be armed and some other simple commands work but soon after there is a 'API call timed out' error and control is lost. Additionally functions taking max_wait_seconds parameter freeze the editor for duration of this value, others freeze editor altogether. 
Can flying API be used that way or is it a totally wrong idea?

**Comment by sytelus** [comment]
I think this happens because now your client and server both runs on the same thread. One way to mitigate this is to make sure your client code runs on separate thread. I'm wondering why you need to do this, however. You can also use instance of DroneApi class directly that you can get from MultiRotorConnector instance (but still you need to run client code on separate thread).
