### ISSUE TITLE
Placing External Camera's to observe multiple vehicles

### ISSUE THREAD

**Issue by spencerh-b** [microsoft/AirSim#610]
Is it possible to place stationary external camera's above the map and have them all record what multiple vehicles in the environment? I need at least two camera's recording from above. I tried to implement this by my self, but I was unable to figure out all the bugs.

1) Manual View Mode isn't working as a default.

2) Unable to find external camera if the Camera Director and BP camera are placed in the map and attached.

**Comment by spencerh-b** [comment]
in the mean time i have just place two stationary multi rotors to provide images.

**Comment by msb336** [comment]
You can do this by creating a [camera blueprint](https://docs.unrealengine.com/en-US/Gameplay/HowTo/UsingCameras/Blueprints/index.html) which tracks the player pawn (use the `getPlayerPawn` blueprint node). You can bind the camera view to a keybinding by opening the level blueprint, adding the camera actor to the blueprint,  and following the blueprint outlined in step nine of the above link. Instead of using `Event BeginPlay`, use a keybind event of your choice.
