### ISSUE TITLE
cannot open city environment binary

### ISSUE THREAD

**Issue by ldhblue3933** [Microsoft/AirSim#642]
![0114](https://user-images.githubusercontent.com/33779033/33374289-de56bc02-d548-11e7-8cca-34dc1c7771ec.jpg)

 when i doubleclicked run.bat file in CityEnviron folder, i cannot open file with this error. how can i fix it?

**Comment by n1ckfg** [comment]
Remove the line in settings.json where you set UAV or car, that fixed it for me. (Save a backup so you can restore after you're done trying the city demo.)

**Comment by sytelus** [comment]
This is because we try to set stencil IDs for all the meshes at startup (this is required for segmentation view). City environment is pretty big and apparently render thread is timing out. In the new version I have put it out as 1.1.7 release, I've disabled setting stencil IDs. This means segmentation won't be available but you won't get this error for now.

**Comment by ldhblue3933** [comment]
i have changed settings.json into initial one but failed to open city environment. but i can open it with version 1.1.7 release. i thank you for the reply and fixing it.

**Comment by lcyawym** [comment]
@sytelus  Hello, I download the cityEnViron. but I can't use 7.zip to extract in window.When I extract it , it occurs some error such as "header error". When I run the CityEnviron.sh. it occurs "error while loading shared libraries: libopenvr_api.so: cannot open shared object file: No such file or directory"
