### ISSUE TITLE
error appeared when I tried to control the car

### ISSUE THREAD

**Issue by Mikemraz** [Microsoft/AirSim#711]
code:
`
while (True):
    car_state = client.getCarState()
 ......
`

error:
> ---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-7-0c9a7881c624> in <module>()
      1 while (True):
----> 2     car_state = client.getCarState()
      3 
      4     if (car_state.speed < 5):
      5         car_controls.throttle = 1.0

C:/Users/Mike Mraz/AirSim/PythonClient\AirSimClient.py in getCarState(self)
    554     def getCarState(self):
    555         state_raw = self.client.call('getCarState')
--> 556         return CarState.from_msgpack(state_raw)

C:/Users/Mike Mraz/AirSim/PythonClient\AirSimClient.py in from_msgpack(cls, encoded)
     24         obj = cls()
     25         #obj.__dict__ = {k.decode('utf-8'): (from_msgpack(v.__class__, v) if hasattr(v, "__dict__") else v) for k, v in encoded.items()}
---> 26         obj.__dict__ = { k : (v if not isinstance(v, dict) else getattr(getattr(obj, k).__class__, "from_msgpack")(v)) for k, v in encoded.items()}
     27         #return cls(**msgpack.unpack(encoded))
     28         return obj

C:/Users/Mike Mraz/AirSim/PythonClient\AirSimClient.py in <dictcomp>(.0)
     24         obj = cls()
     25         #obj.__dict__ = {k.decode('utf-8'): (from_msgpack(v.__class__, v) if hasattr(v, "__dict__") else v) for k, v in encoded.items()}
---> 26         obj.__dict__ = { k : (v if not isinstance(v, dict) else getattr(getattr(obj, k).__class__, "from_msgpack")(v)) for k, v in encoded.items()}
     27         #return cls(**msgpack.unpack(encoded))
     28         return obj

AttributeError: 'CarState' object has no attribute 'collision'

**Comment by sytelus** [comment]
I found the issue and it's now fixed in [this commit](https://github.com/Microsoft/AirSim/commit/b1ecc13f500a05d355dbe7aca65c200a3f4e0051). Please get latest. If you had done local changes to workaround this issue and then you might want to revert them first. 

Also, please note that there is slight change in APIs. Specifically, CarState structure now has [full kinematics](https://github.com/Microsoft/AirSim/blob/b1ecc13f500a05d355dbe7aca65c200a3f4e0051/PythonClient/AirSimClient.py#L159). This now allows you to get much more ground truth information about car's state in `kinematics_true` than just position and velocity.

Duplicate issues:

- https://github.com/Microsoft/AirSim/issues/708
- https://github.com/Microsoft/AirSim/issues/699
- https://github.com/Microsoft/AirSim/issues/711
