### ISSUE TITLE
Object Pose, Compiling City and Car Models

### ISSUE THREAD

**Issue by alexiip** [Microsoft/AirSim#728]
I have three questions:

1. Is it possible to also get the object pose while getting depth or segmentation? I see that there is a function called `pose = client.simGetObjectPose("MyObject");` but it does not seem to accept a wildcard and it seems to give you the pose of the object anywhere in the world, not of the one(s) which the camera sees. Is there a way to get an object pose of the segmented/wildcard objects which the camera sees?
2. How can I compile a modified version of AirSim with the City environment? I can't seem to find the City environment in the repo, and I don't see the one with the moving cars and people anywhere in the Unreal store. I am trying to find a way to either use existing APIs or to recompile the City in such a way as to also recover the object pose from the segmentation + depth image.
3. Where can I find the car models which are found in the City environment.

Thanks a lot for the help.

**Comment by sytelus** [comment]
simGetObjectPose is described well in docs:

* `simGetObjectPose`: Gets the pose of specified object in Unreal environment. Here the object means "actor" in Unreal terminology. They are searched by tag as well as name. To add tag to actor, go to object in Unreal Editor, click on it, look for [Tags property](https://answers.unrealengine.com/questions/543807/whats-the-difference-between-tag-and-tag.html), click "+" sign and add some string value. If multiple actors have same tag then the first match is returned. If no matches are found then NaN pose is returned.

So this API finds the object using tags. This is because names you see in Unreal editor aren't unfortunately available at runtime.

The City environment unfortunately has many copyrighted assets and hence we cannot freely distribute these asset files or environment source. We can only distribute binaries. This environment we created in-house with help of artists and is still under development.

Some of the car models are available in Unreal Marketplace while others we have created in house.
