### ISSUE TITLE
Support for object bounding box reporting

### ISSUE THREAD

**Issue by ghexp** [Microsoft/AirSim#74]
Adding support to the simulator to include bounding boxes in addition to segmented objects will help with training trackers similar to [UAV123](https://ivul.kaust.edu.sa/Pages/Dataset-UAV123.aspx). UAVSimUE4 from the UAV123 team provides an example of this functionality via UE:
https://github.com/IVUL-KAUST/UAVSimUE4/blob/master/Plugins/Simulator/Source/Simulator/Private/SimulatorFunctions.cpp

**Comment by sytelus** [comment]
HI @ghexp, we have functionality to retrieve images from sim however higher level features like adding bounding box probably should be outside of simulator. The reason is that such features have many varied requirements with various different algorithms and customization possible. Its best that people write their own code for such features (or use established libraries they preferred). May be we can enable some sort of extension model in future so it would be very easy to plug-in these kind of functionality and share it with other users.
