### ISSUE TITLE
PointCloud generation

### ISSUE THREAD

**Issue by badabook** [microsoft/AirSim#745]
I tryed to generate a pointcloud using a point_cloud.py update. The modifications are due to the fact that there is no more "Depth" as ImageType in AirSim, here is the code: 

```
while True:
    rawImage = client.simGetImage(0, AirSimImageType.DepthVis)
    if (rawImage is None):
        print("Camera is not returning image, please check airsim for error messages")
        sys.exit(0)
    else:
        png = cv2.imdecode(np.frombuffer(rawImage, np.uint8) , cv2.IMREAD_UNCHANGED)
        gray = cv2.cvtColor(png, cv2.COLOR_BGR2GRAY)
        Image3D = cv2.reprojectImageTo3D(gray, projectionMatrix)
        savePointCloud(Image3D, outputFile)
        print("saved " + outputFile)
        sys.exit(0)

    key = cv2.waitKey(1) & 0xFF;
    if (key == 27 or key == ord('q') or key == ord('x')):
        break;
```
But that's what i obtain:

![2018-01-18 6](https://user-images.githubusercontent.com/35538685/35098427-5e324e64-fc54-11e7-9390-6bcb5fa7c157.png)

This is the link to Sketchfab: https://skfb.ly/6vQ7T

What am I doing wrong?

**Comment by sytelus** [comment]
Try to use DepthPlanner and DepthPerspective instead of DepthVis. The DepthPerspective mode generates depth as if single ideal camera will generate depth. Cameras use perspective transform so parallel rays are no longer parallel after transformation. [See here](https://medium.com/retronator-magazine/game-developers-guide-to-graphical-projections-with-video-game-examples-part-1-introduction-aa3d051c137d) for more info. The DepthPlanner mode keeps parallel rays parallel.

Also, please note that point_cloud.py was an external contribution and I personally haven't tested it. It would be great if you had like to work on this script, make it better and contribute improved version :). I've already updated this script to use the latest APIs.

**Comment by badabook** [comment]
Thank you for the answer! I will work on this script for a new update!

**Comment by kshitijgoel007** [comment]
@badabook @sytelus Were you able to register point cloud correctly? I am trying to make a local map using the depth perspective images, but I am getting a radial distortion.

If you go really close to a wall (where the pfm array should be entirely filled with same value), after printing the array it seems it has outward radial distortion.

Here is an example 
![image](https://user-images.githubusercontent.com/7077226/38053124-4559600c-32a1-11e8-9fc2-a105fe7d2947.png)
On the right hand side there is the airsim scene from the zen garden environment and on the left hand side is a registration of the scene using depth images. It seems the depth images are radially outward. Did you guys also observe this?

**Comment by jonyMarino** [comment]
Closed due to inactivity. Doc update pending
