### ISSUE TITLE
Arming Denied：Preflight check have failed.

### ISSUE THREAD

**Issue by zf223669** [Microsoft/AirSim#78]
Hi, I have met a problem that i used the DroneShell to control the drone, however, when i inputted the command arm, it showed that Arming Denied：Preflight check have failed.

**Comment by sytelus** [comment]
Its most likely a set up problem. I have seen this happening before but can't recall the context. The way to debug this issue is simple: Use QGroundControl to connect to Pixhawk and see if there is anything red. Then try to arm and takeoff from within QGroundControl. If that works then it should work in AIrSim as well. Also, try out latest code (there were few API issues were resolved recently).

**Comment by TomorrowIsAnOtherDay** [comment]
Then try to arm and takeoff from within QGroundControl.

**Comment by TomorrowIsAnOtherDay** [comment]
How to arm and takeoff from within QGroundControl?

**Comment by lovettchris** [comment]
this thread is actually closed already... please open a new one, but QGroundControl probably has it's own forums somewhere.
